
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Original template: https://github.com/MengZheK/kangblog.github.io

title: L.A.B. - Leo Archer & Beyond
subtitle: Welcome to the LAB!
email: leoarcher37(at)gmail.com_NOSPAM
description: >- # this means to ignore newlines until "baseurl:"
  learn and let learn
avatarTitle: 李安之
avatarDesc: 数据 语言 生活 
url: "https://leoarcher.github.io/"
twitter_username: leoarcher37
github_username:  leoarcher

# Build settings
theme: minima
plugins:
  - jekyll-feed


permalink: /:short_year:i_month:i_day.html

# Format

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: blog

# Navigation buttons in the front page.
nav:
    - {title: archive, description: archive, url: '/archive'}   
    - {title: tag, description: tag, url: '/tag'}   
    - {title: comment, description: comment, url: '/comment'}
    - {title: resource, description: resource, url: '/resource'}
    - {title: about, description: about, url: '/about'}

          
# Google Analytics
ga:
    id: G-5E82R646ST

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


